start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

[gaps]
inner.horizontal = 0
inner.vertical   = 0
outer.left       = 0
outer.bottom     = 0
outer.top        = 0
outer.right      = 0

[mode.main.binding]
alt-semicolon = 'focus-back-and-forth'

# Layouts
alt-q = 'layout v_accordion'
alt-w = 'layout h_accordion'
alt-e = 'layout tiles horizontal vertical'

# Workspaces
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'

alt-shift-r = 'reload-config'
alt-shift-space = 'layout floating tiling'

# Atalhos de apps (letras livres)
alt-n = 'exec-and-forget open -a Notion'
alt-t = 'exec-and-forget open -a WezTerm'
alt-b = 'exec-and-forget open -a Bitwarden'
alt-g = 'exec-and-forget open -u https://github.com'
alt-f = 'exec-and-forget open -a Finder'

# Workspace assignments
[[on-window-detected]]
if.app-id = 'notion.id'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-id = 'md.obsidian'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-id = 'com.apple.Notes'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-id = 'dev.zed.Zed'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'com.hnc.Discord'
run = 'move-node-to-workspace 4'


# Float rules
[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.imagestudiopro.ScreenBrush'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.mail'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.QuickTimePlayerX'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.systempreferences'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'org.localsend.localsendApp'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'cc.ffitch.shottr'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.bitwarden.desktop'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = 'layout floating'
