tap "nikitabobko/tap"

cask "figma"
cask "adobe-creative-cloud"
cask "visual-studio-code"
cask "antigravity"
cask "notion"
cask "obsidian"
cask "clickup"
cask "google-chrome"
cask "discord"
cask "raycast"
cask "shottr"
cask "logi-options-plus"
cask "jordanbaird-ice"
cask "keyboard-maestro"
cask "nikitabobko/tap/aerospace"
cask "latest"
